- demo.js
- package-lock.json
> First commit on branch Lauren. Created function sayHello.

- demo.js
> Olivia first push

- seed.js
> populated user data

- client/app.js
- client/components/navbar.js
- public/style.css
Updated navbar to a react bootstrap navbar
> converted navbar to react-bootstrap nav-bar and added basic css

- script/seed.js
> added some more shoes

- client/app.js
- client/components/orders.js
- client/store/index.js
- client/store/orders.js
- package-lock.json
- package.json
- script/seed.js
- server/api/index.js
- server/api/orders.js
> All orders irina

- client/store/user.js
- client/store/user.spec.js
added tests for GET_ALL_USERS and GET_SINGLE_USER
> Lauren tests

- client/app.js
- client/components/admin-dashboard.js
> start of admin dashboard - incorporated add brand and add shoe forms

- client/app.js
- client/components/AllShoes.js
- client/components/navbar.js
- client/store/index.js
- client/store/shoes.js
- package-lock.json
- package.json
- public/style.css
- server/api/shoes.js
---
Noticed that my updates weren't reflected. Should we merge again?
> Updating main branch?

- client/app.js
- client/components/auth-form.js
- client/components/navbar.js
- client/store/auth.js
- server/auth/google.js
google auth + email / password login & signup
> feat: added form fields, fix: updated boilermaker routing for oauth

- client/app.js
- client/components/AllShoes.js
- client/components/get-shoe-price.js
- client/components/single-shoe.js
- client/store/index.js
- client/store/shoes.js
- server/db/models/index.js
- server/db/models/orders.js
- server/db/models/purchased.js
- server/db/models/shoes.js
> feat: updated/ added shoe, order, purchased models; added 

- client/components/AllShoes.js
- client/components/homepage.js
- client/components/navbar.js
- client/components/single-shoe.js
- client/routes.js
- public/index.html
> New routes

- client/components/AllShoes.js
- client/components/get-shoe-price.js
- client/components/single-shoe.js
- client/components/update-shoe-form.js
- client/routes.js
- client/store/shoes.js
- client/store/singleShoe.js
- client/store/singleShoe.spec.js
- seed.js
- server/api/shoes.js
> work on shoe components and routes

- client/components/AllShoes.js
- client/components/homepage.js
- client/routes.js
- client/store/index.js
- public/style.css
> freat: updated main page

- client/components/navbar.js
- client/store/cart.js
> feat: starting redux cart

- client/components/brands.js
- client/components/navbar.js
- client/components/single-brand.js
- client/components/single-shoe.js
- client/routes.js
- client/store/brands.js
- client/store/cart.js
- client/store/index.js
- client/store/singleBrand.js
- public/style.css
- script/seed.js
- server/api/brands.js
- server/api/index.js
- server/api/shoes.js
- server/db/models/index.js
> Please run npm seed, changes to the db

- client/components/cart.js
- client/components/orders.js
- client/components/single-shoe.js
- client/routes.js
- client/store/orders.js
- server/api/users.js
> Olivia & Lauren - Cart

- client/components/AllShoes.js
- client/components/cart.js
- client/components/single-shoe.js
- client/store/orders.js
- client/store/singleShoe.js
- public/style.css
- server/api/orders.js
- server/api/users.js
> feat: cart updates

- ZAPDOS-README/tiers.md
- client/components/cart.js
- client/store/brands.spec.js
- client/store/orders.js
- server/api/users.js
> Fixed remove item, wrote test for brands

- client/components/cart.js
- client/components/orders.js
- client/store/orders.js
- server/api/users.js
> fix: changed increase button

- client/components/AllShoes.js
- client/components/cart-quantity-button.js
- client/components/cart.js
> fix: increase decrease quantity

- client/components/cart.js
- client/components/checkout-billing-form.js
- client/components/checkout-complete.js
- client/components/checkout.js
- client/components/single-shoe.js
- client/components/user-home.spec.js
- client/routes.js
- client/store/orders.js
- server/api/orders.js
- server/api/orders.spec.js
- server/api/users.js
- server/api/users.spec.js
> checkout and tests

- server/api/orders.spec.js
> test: change

- client/components/AllShoes.js
- client/components/cart.js
- client/components/single-shoe.js
- client/routes.js
- server/api/orders.js
- server/api/users.js
- server/db/models/shoes.js
> fix: fix the buttons, redirect to cart

- client/components/AllShoes.js
- client/components/brands.js
- client/components/single-shoe.js
- public/style.css
- script/seed.js
> Connected shoes to brands, flex-box for brands and shoes

- client/components/single-brand.js
> fix: single brand view

- client/components/cart.js
- client/components/orders.js
- client/components/shoe-form.js
- client/components/single-shoe.js
- client/components/update-shoe.js
- client/store/singleShoe.spec.js
> cart, total order/cart price, single shoe minor edits

- client/components/all-users.js
- client/components/card.js
- client/components/single-user.js
- client/components/user-form.js
- client/components/user-home.js
- client/store/auth.js
- client/store/user.js
- server/api/users.js
> feat: update user profile. feat: delete user as admin

- client/components/brands.js
- client/components/brands.spec.js
- client/store/orders.js
- client/store/orders.spec.js
> test: added tests

- client/components/shoe-form.js
- server/api/shoes.spec.js
- server/api/users.spec.js
- server/db/models/index.js
- server/db/models/orders_purchased.spec.js
- server/db/models/shoes.js
- server/db/models/shoes.spec.js
> test: sequelize shoe and orders models

- client/components/AllShoes.js
- client/components/brands.js
- client/components/checkout-billing-form.js
- client/components/checkout.js
- client/components/footer.js
- client/components/homepage.js
- client/components/single-brand.js
- client/components/single-shoe.js
- public/style.css
- server/db/models/brands.spec.js
> styling: css

- client/components/homepage.js
- client/components/navbar.js
- client/components/single-brand.js
> feat: started dropdown navbar brands

- client/components/AllShoes.js
- client/components/single-shoe.js
- package-lock.json
- package.json
- public/style.css
> Test irina

- client/app.js
- client/components/single-shoe.js
- public/style.css
- script/seed.js
- server/api/orders.js
> Local storage

- client/components/AllShoes.js
- client/components/cart.js
- client/components/single-shoe.js
- client/store/orders.js
- server/api/orders.js
- server/api/users.js
- server/db/models/purchased.js
> Olivia - cart working

- client/components/add-shoe.js
- client/components/admin-dashboard.js
- client/components/card.js
- client/components/navbar.js
- client/components/orders.js
- client/components/update-user.js
- client/components/user-home.js
- client/store/auth.js
- client/store/brands.js
- client/store/orders.js
- client/store/shoes.js
- client/store/user.js
- server/api/brands.js
- server/api/orders.js
- server/api/users.js
- server/api/utils.js
- server/auth/index.js
- server/db/models/shoes.js
> Lauren branch

- client/components/user-home.js
- client/store/auth.js
- client/store/user.js
> fix: bug on user profile rendering updates

- client/components/auth-form.js
> fix: oauth link bug

- client/components/cart.js
- public/style.css
> feat: style cart
